1.

CREATE SCHEMA homework1 
AUTHORIZATION Information_schema


2.


CREATE TABLE [dbo].[Deposit](
	[DepositID] [int] NOT NULL,
	[DepositAmount] [decimal](5, 2) NULL,
	[DepositTypeKey] [tinyint] NULL,
	[DepositInterestRate] [decimal](6, 4) NULL,
	[Isresident] [bit] NOT NULL,
	[DepositProductKey] [tinyint] NULL
) ON [PRIMARY]



3.

alter table [dbo].[Deposit]
alter column [DepositTypeKey] [smallint] null

4.
CREATE DATABASE [HomeWork1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HomeWork1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HomeWork1.mdf' , SIZE = 8192KB , MAXSIZE = 512000KB , FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'HomeWork1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HomeWork1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 5%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HomeWork1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HomeWork1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HomeWork1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HomeWork1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HomeWork1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HomeWork1] SET ARITHABORT OFF 
GO

ALTER DATABASE [HomeWork1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HomeWork1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HomeWork1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HomeWork1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HomeWork1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HomeWork1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HomeWork1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HomeWork1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HomeWork1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HomeWork1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HomeWork1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HomeWork1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HomeWork1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HomeWork1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HomeWork1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HomeWork1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HomeWork1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HomeWork1] SET RECOVERY FULL 
GO

ALTER DATABASE [HomeWork1] SET  MULTI_USER 
GO

ALTER DATABASE [HomeWork1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HomeWork1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HomeWork1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HomeWork1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HomeWork1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HomeWork1] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HomeWork1] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HomeWork1] SET  READ_WRITE 
GO


